language: php

php:
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update

install:
  - composer install --no-interaction --prefer-dist --no-suggest

script: vendor/bin/phpunit
